Merge class LinearGetValues
UMD-AOSC/OISSTv3 pull request #31
Opened 2020-12-02 18:06 UTC by loganchen39

@travissluka passed all the tests. Please check the lineargetvalues.yml where I didn't add anything under "linear getvalues test: ", not sure what to add. Let me know if it's ok. 

close #21.

2020-12-04 20:06 UTC, travissluka requested changes
Only small comment is to delete the `GeoVaLsWrapperAD` class as it isn't needed.

That's fine about no parameters being added to the yaml section, it seems the default values for the test are acceptable.

2020-12-04 20:06 UTC, travissluka commented on src/umdsst/GetValues/CMakeLists.txt
> +    GeoVaLsWrapperAD.f90
Delete these, I don't see why they're needed. Just use  `GeoVaLsWrapper`, they're essentially the same.

2020-12-04 20:36 UTC, loganchen39 commented on src/umdsst/GetValues/CMakeLists.txt
> +    GeoVaLsWrapperAD.f90
@travissluka My understanding of the difference is that, in GeoVaLsWrapper.f90, we copy data from interpolated results to geovals as indicated below at line 57:
geovals%geovals(ivar)%vals(:,i) = field_data(:,i)

while for function void LinearGetValues::fillGeoVaLsTL(...), we need to copy the data from geovals as indicated below at line 52 within file GeoVaLsWrapperAD.f90
field_data(:,i) = geovals%geovals(ivar)%vals(:,i)
and then do the backward interpolation.

Is my understanding correct? If so, are you suggesting that I combine these two (files and classes) together? That makes sense.

2020-12-05 00:07 UTC, travissluka commented on src/umdsst/GetValues/CMakeLists.txt
> +    GeoVaLsWrapperAD.f90
you're absolutely correct! Sorry, I'm not sure what I was thinking (been a long week??)
Those wrapper classes will be deleted eventually anyway once GeoVaLs is refactored by the JEDI team.

Looks good. I'll merge

2020-12-05 00:07 UTC, travissluka approved these changes

2020-12-05 00:08 UTC, merged